Adding WordCounter project to the repository. [Hacktoberfest]
VidhiBhatt01/The-Frontend-Store pull request #108
Opened 2023-10-14 15:22 UTC by thevirengarg

Issue #105 
Adding a front end project to the repo, which calculates typing speed of the user and helps in practicing speed typing.
This website is created using HTML, CSS, javascript.

![Screenshot (287)](https://github.com/VidhiBhatt01/The-Frontend-Store/assets/111726483/0775dd5b-9abc-48ff-a39d-adc19bf30a0b)

![Screenshot (289)](https://github.com/VidhiBhatt01/The-Frontend-Store/assets/111726483/edb20ce5-c8bf-4776-b4c0-1f276595b967)

![Screenshot (288)](https://github.com/VidhiBhatt01/The-Frontend-Store/assets/111726483/7b6447e4-d2ed-49c4-a103-d2d5890534cb)

2023-10-14 15:23 UTC, thevirengarg commented
@VidhiBhatt01 Please review this Pull request.

2023-10-14 15:24 UTC, thevirengarg commented
@VidhiBhatt01 Open index.html file in your browser to view the website

2023-10-15 10:47 UTC, VidhiBhatt01 requested changes
Very poor file naming. Rename index3, indexx, stylee files. Follow a uniform naming structure like main1, main2, style1, style2.... or name it something more suitable. 

Clean up your existing files, ident them properly and remove multiple extra lines

2023-10-15 10:47 UTC, VidhiBhatt01 commented on Projects/WordCounter/stylee.css
> +
nit: Extra line

2023-10-15 10:47 UTC, VidhiBhatt01 commented on Projects/WordCounter/stylee.css
> +
extra line

2023-10-15 10:47 UTC, VidhiBhatt01 commented on Projects/WordCounter/stylee.css
> +
extra lines

2023-10-15 10:48 UTC, VidhiBhatt01 commented
> @VidhiBhatt01 Open index.html file in your browser to view the website

You should deploy it somewhere and attach the deployed link in the PR description

2023-10-15 15:11 UTC, closed without merging