Breakout-Classic-game
VidhiBhatt01/The-Frontend-Store pull request #36
Opened 2022-10-11 16:21 UTC by aytida0606

Breakout Game #35

2022-10-13 17:15 UTC, VidhiBhatt01 requested changes
Just add a readme file that explains how to play the game

2022-10-13 17:15 UTC, VidhiBhatt01 commented
https://deploy-preview-36--cozy-pastelito-ffe9b3.netlify.app/games/breakout%20clasic/

2022-10-14 04:18 UTC, aytida0606 commented
@VidhiBhatt01  changes added.

2022-10-14 13:02 UTC, VidhiBhatt01 approved these changes

2022-10-14 13:03 UTC, merged